<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

$tables = get_posts( [
    'post_type'      => 'ai_pricing_table',
    'post_status'    => 'publish',
    'posts_per_page' => -1,
    'orderby'        => 'date',
    'order'          => 'DESC',
] );

ob_start();
?>
<h1>Import / Export</h1>
<p>Download all pricing tables as a versioned JSON backup or import a previous export into this site.</p>

<div class="ai-admin-card">
    <h2>Export All Tables</h2>
    <p><?php echo esc_html( count( $tables ) ); ?> saved tables will be included in the export file.</p>
    <form method="post" action="">
        <?php wp_nonce_field( 'ai_pricing_export_tables', 'ai_pricing_import_export_nonce' ); ?>
        <input type="hidden" name="ai_pricing_action" value="export_tables" />
        <?php submit_button( 'Download JSON Backup', 'primary', 'submit', false ); ?>
    </form>
</div>

<div class="ai-admin-card">
    <h2>Import Tables</h2>
    <p>Paste a JSON export generated by this plugin. Each imported table will be created as a new hidden pricing-table record.</p>
    <form method="post" action="">
        <?php wp_nonce_field( 'ai_pricing_import_tables', 'ai_pricing_import_export_nonce' ); ?>
        <input type="hidden" name="ai_pricing_action" value="import_tables" />
        <p>
            <label for="ai_pricing_import_json" class="screen-reader-text">Import JSON</label>
            <textarea id="ai_pricing_import_json" name="ai_pricing_import_json" rows="14" class="large-text code" placeholder='{"plugin":"ai-pricing-table","tables":[...]}'></textarea>
        </p>
        <?php submit_button( 'Import Pricing Tables', 'secondary', 'submit', false ); ?>
    </form>
</div>

<div class="ai-admin-card">
    <h2>Format Notes</h2>
    <ul>
        <li>Exports include plugin version, schema version, site URL, and all saved pricing-table records.</li>
        <li>Imports validate each table independently, so invalid entries are skipped without stopping the whole import.</li>
        <li>Manual tables are migrated through the same normalization layer used by the builder and frontend renderer.</li>
    </ul>
</div>
<?php
$content = ob_get_clean();

include __DIR__ . '/layout.php';
